language: python
python:
- 3.5
- 3.6
services:
- rabbitmq
env:
  global:
  - AMMOO_TEST_VIRTUALHOST=/
  - AMMOO_TEST_AMQP_HOST=localhost
install:
- pip install .[test]
before_script:
- if test -z $PYTHONPATH; then export PYTHONPATH=tests/lib; else export PYTHONPATH=$PYTHONPATH:tests/lib; fi
script:
- env
- pwd
- pytest tests
notifications:
  email: true
